In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

# Import our input dataset
charity_df = pd.read_csv('charity_data.csv')
charity_df.head()

C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Generate our categorical variable list
charity_cat = charity_df.dtypes[charity_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
charity_df[charity_cat].nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
dtype: int64

In [3]:
# Check the unique value counts to see if binning is required
charity_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2380        1
C3700        1
C4500        1
C2170        1
C4200        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [4]:
# Check the unique value counts to see if binning is required
charity_df.APPLICATION_TYPE.value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T15        2
T29        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Check the unique value counts to see if binning is required
charity_df.INCOME_AMT.value_counts()

0                24388
25000-99999       3747
100000-499999     3374
1M-5M              955
1-9999             728
10000-24999        543
10M-50M            240
5M-10M             185
50M+               139
Name: INCOME_AMT, dtype: int64

In [6]:
# can drop NAME 
charity_df= charity_df.drop(columns="NAME")
charity_df= charity_df.drop(columns="EIN")
classfic_cts = charity_df.CLASSIFICATION.value_counts()
app_type = charity_df.APPLICATION_TYPE.value_counts()

# Determine which values to replace
replace_classific = list(classfic_cts[classfic_cts < 100].index)

# Replace in DataFrame
for count in replace_classific:
    charity_df.CLASSIFICATION = charity_df.CLASSIFICATION.replace(count,"Other")
    
# Determine which values to replace
replace_app = list(app_type[app_type < 100].index)

# Replace in DataFrame
for count in replace_app:
    charity_df.APPLICATION_TYPE = charity_df.APPLICATION_TYPE.replace(count,"Other")


# Check to make sure binning was successful
charity_df.CLASSIFICATION.value_counts()
charity_df.APPLICATION_TYPE.value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [7]:
charity_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [8]:
charity_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [9]:
# Generate our categorical variable list
charity_cat = charity_df.dtypes[charity_df.dtypes == "object"].index.tolist()


# Check the number of unique values in each column
charity_df[charity_cat].nunique()

APPLICATION_TYPE          10
AFFILIATION                6
CLASSIFICATION            12
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [10]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(charity_df[charity_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(charity_cat)
encode_df.head()

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,APPLICATION_TYPE_T9,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
# Merge one-hot encoded features and drop the originals
charity_df = charity_df.merge(encode_df,left_index=True, right_index=True)
charity_df = charity_df.drop(charity_cat,1)
charity_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [12]:
# Split our preprocessed data into our features and target arrays
y = charity_df["IS_SUCCESSFUL"].values
X = charity_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
len(X_train_scaled[0])

50

In [14]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  number_input_features * 3
hidden_nodes_layer2 = number_input_features
hidden_nodes_layer3 = 25

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
#nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2))
#nn.add(tf.keras.layers.LeakyReLU(alpha=0.05))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the Sequential model together and customize metrics
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

WARNING:tensorflow:From C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From C:\Users\nethr\anaconda3\envs\PythonData\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [15]:
# Train the model 
fit_model = nn.fit(X_train_scaled, y_train, epochs=200) 
# Evaluate the model using the test data 
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/200
25724/25724 [==============================] - 1s 30us/sample - loss: 0.5679 - acc: 0.7221
Epoch 2/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5535 - acc: 0.7304
Epoch 3/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5505 - acc: 0.7321
Epoch 4/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5482 - acc: 0.7328
Epoch 5/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5472 - acc: 0.7330
Epoch 6/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5458 - acc: 0.7350
Epoch 7/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5454 - acc: 0.7345
Epoch 8/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5447 - acc: 0.73470s - loss: 0.5540 -
Epoch 9/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5438 - acc: 0.7361
Epoch 10/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5428 - acc: 0.7366
Epoch 11/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5427 - acc: 0.7366
Epoch 12/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5416 - acc: 0.73690s - loss: 0.5424 -
Epoch 13/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5422 - acc: 0.7370
Epoch 14/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5413 - acc: 0.7373
Epoch 15/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5414 - acc: 0.7372
Epoch 16/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5410 - acc: 0.7374
Epoch 17/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5402 - acc: 0.7379
Epoch 18/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5400 - acc: 0.7386
Epoch 19/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5402 - acc: 0.7383
Epoch 20/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5400 - acc: 0.7396
Epoch 21/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5391 - acc: 0.7385
Epoch 22/200
25724/25724 [==============================] - ETA: 0s - loss: 0.5388 - acc: 0.738 - 1s 27us/sample - loss: 0.5392 - acc: 0.7381
Epoch 23/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5391 - acc: 0.7388
Epoch 24/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5386 - acc: 0.7395
Epoch 25/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5386 - acc: 0.7395
Epoch 26/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5379 - acc: 0.73910s - loss: 0.5375 - acc: 0.739
Epoch 27/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5383 - acc: 0.7390
Epoch 28/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5375 - acc: 0.74000s - loss: 0.5364
Epoch 29/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5376 - acc: 0.73950s - loss: 0.5324 -
Epoch 30/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5373 - acc: 0.7399
Epoch 31/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5371 - acc: 0.7404
Epoch 32/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5368 - acc: 0.7402
Epoch 33/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5372 - acc: 0.7396
Epoch 34/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5374 - acc: 0.7393
Epoch 35/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5367 - acc: 0.7405
Epoch 36/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5364 - acc: 0.7407
Epoch 37/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5364 - acc: 0.7403
Epoch 38/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5357 - acc: 0.7398
Epoch 39/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5358 - acc: 0.7406
Epoch 40/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5357 - acc: 0.7396
Epoch 41/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5359 - acc: 0.7407
Epoch 42/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5355 - acc: 0.7404
Epoch 43/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5349 - acc: 0.7402
Epoch 44/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5348 - acc: 0.7399
Epoch 45/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5357 - acc: 0.7413
Epoch 46/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5350 - acc: 0.74020s - loss: 0.5447 -
Epoch 47/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5353 - acc: 0.7407
Epoch 48/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5352 - acc: 0.7405
Epoch 49/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5349 - acc: 0.7414
Epoch 50/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5349 - acc: 0.7415
Epoch 51/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5347 - acc: 0.7407
Epoch 52/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5345 - acc: 0.7412
Epoch 53/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5346 - acc: 0.74110s - loss: 0.5329 - acc: 0.7
Epoch 54/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5342 - acc: 0.7405
Epoch 55/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5345 - acc: 0.7410
Epoch 56/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5344 - acc: 0.7408
Epoch 57/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5340 - acc: 0.7407
Epoch 58/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5340 - acc: 0.7416
Epoch 59/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5341 - acc: 0.7417
Epoch 60/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5339 - acc: 0.7413
Epoch 61/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5340 - acc: 0.7418
Epoch 62/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5332 - acc: 0.7419
Epoch 63/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5334 - acc: 0.7414
Epoch 64/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5335 - acc: 0.7414
Epoch 65/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5342 - acc: 0.7415
Epoch 66/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5332 - acc: 0.7418
Epoch 67/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5332 - acc: 0.7416
Epoch 68/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5331 - acc: 0.7409
Epoch 69/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5327 - acc: 0.7412
Epoch 70/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5328 - acc: 0.7418
Epoch 71/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5335 - acc: 0.7430
Epoch 72/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5330 - acc: 0.7418
Epoch 73/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5326 - acc: 0.7417
Epoch 74/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5320 - acc: 0.7419
Epoch 75/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5330 - acc: 0.7418
Epoch 76/200
25724/25724 [==============================] - 1s 30us/sample - loss: 0.5329 - acc: 0.7421
Epoch 77/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5326 - acc: 0.7413
Epoch 78/200

25724/25724 [==============================] - 1s 28us/sample - loss: 0.5322 - acc: 0.74220s - loss: 0.5307 - acc:
Epoch 79/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5326 - acc: 0.7415
Epoch 80/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5327 - acc: 0.7421
Epoch 81/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5325 - acc: 0.7416
Epoch 82/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5324 - acc: 0.7416
Epoch 83/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5320 - acc: 0.74310s - loss: 0.5262 - acc:
Epoch 84/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5325 - acc: 0.7422
Epoch 85/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5322 - acc: 0.7421
Epoch 86/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5322 - acc: 0.7424
Epoch 87/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5322 - acc: 0.7414
Epoch 88/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5324 - acc: 0.7421
Epoch 89/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5321 - acc: 0.7418
Epoch 90/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5321 - acc: 0.7426
Epoch 91/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5323 - acc: 0.7425
Epoch 92/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5325 - acc: 0.7417
Epoch 93/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5318 - acc: 0.7420
Epoch 94/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5315 - acc: 0.7427
Epoch 95/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5314 - acc: 0.7421
Epoch 96/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5319 - acc: 0.7429
Epoch 97/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5314 - acc: 0.7418
Epoch 98/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5312 - acc: 0.7427
Epoch 99/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5315 - acc: 0.7418
Epoch 100/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5312 - acc: 0.7424
Epoch 101/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5311 - acc: 0.7423
Epoch 102/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5316 - acc: 0.7424
Epoch 103/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5309 - acc: 0.7426
Epoch 104/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5311 - acc: 0.7415
Epoch 105/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5316 - acc: 0.7416
Epoch 106/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5312 - acc: 0.7415
Epoch 107/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5310 - acc: 0.7423
Epoch 108/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5310 - acc: 0.74130s - loss: 0.5322 - acc:
Epoch 109/200
25724/25724 [==============================] - ETA: 0s - loss: 0.5313 - acc: 0.7418- ETA: 0s - loss: 0.5352 -  - 1s 27us/sample - loss: 0.5311 - acc: 0.7423
Epoch 110/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5309 - acc: 0.7421
Epoch 111/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5309 - acc: 0.7420
Epoch 112/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5307 - acc: 0.7427
Epoch 113/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5304 - acc: 0.7423
Epoch 114/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5308 - acc: 0.7425
Epoch 115/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5305 - acc: 0.7425
Epoch 116/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5311 - acc: 0.7429
Epoch 117/200
25724/25724 [==============================] - ETA: 0s - loss: 0.5302 - acc: 0.742 - 1s 28us/sample - loss: 0.5316 - acc: 0.7411
Epoch 118/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5309 - acc: 0.7429
Epoch 119/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5309 - acc: 0.7426
Epoch 120/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5309 - acc: 0.7414
Epoch 121/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5308 - acc: 0.7430
Epoch 122/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5302 - acc: 0.7430
Epoch 123/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5304 - acc: 0.7418
Epoch 124/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5305 - acc: 0.7425
Epoch 125/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5305 - acc: 0.7425
Epoch 126/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5325 - acc: 0.74210s - loss: 0.5199
Epoch 127/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5303 - acc: 0.7428
Epoch 128/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5299 - acc: 0.7424
Epoch 129/200
25724/25724 [==============================] - ETA: 0s - loss: 0.5305 - acc: 0.7430- ETA: 0s - loss: 0.5287 - acc: 0. - 1s 27us/sample - loss: 0.5306 - acc: 0.7423
Epoch 130/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5302 - acc: 0.7431
Epoch 131/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5301 - acc: 0.7424
Epoch 132/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5302 - acc: 0.7426
Epoch 133/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5305 - acc: 0.7422
Epoch 134/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5310 - acc: 0.7420
Epoch 135/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5304 - acc: 0.7425
Epoch 136/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5298 - acc: 0.7432
Epoch 137/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5296 - acc: 0.7430
Epoch 138/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5306 - acc: 0.7421
Epoch 139/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5299 - acc: 0.7433
Epoch 140/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5298 - acc: 0.74260s - loss: 0.5270 -
Epoch 141/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5299 - acc: 0.7425
Epoch 142/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5302 - acc: 0.7429
Epoch 143/200
25724/25724 [==============================] - 1s 30us/sample - loss: 0.5302 - acc: 0.7427
Epoch 144/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5295 - acc: 0.7423
Epoch 145/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5300 - acc: 0.7425
Epoch 146/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5299 - acc: 0.7428
Epoch 147/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5296 - acc: 0.7430
Epoch 148/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5300 - acc: 0.74270s - loss: 0.5133 -
Epoch 149/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5292 - acc: 0.7423
Epoch 150/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5297 - acc: 0.7429
Epoch 151/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5293 - acc: 0.7429
Epoch 152/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5299 - acc: 0.7436
Epoch 153/200

25724/25724 [==============================] - 1s 27us/sample - loss: 0.5300 - acc: 0.7425
Epoch 154/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5298 - acc: 0.74270s - loss: 0.5417 -
Epoch 155/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5295 - acc: 0.7425
Epoch 156/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5297 - acc: 0.7434
Epoch 157/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5303 - acc: 0.74280s - loss: 0.5320 - acc:
Epoch 158/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5296 - acc: 0.7426
Epoch 159/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5292 - acc: 0.7428
Epoch 160/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5298 - acc: 0.7431
Epoch 161/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5294 - acc: 0.7430
Epoch 162/200
25724/25724 [==============================] - 1s 30us/sample - loss: 0.5293 - acc: 0.7430
Epoch 163/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5291 - acc: 0.7423
Epoch 164/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5292 - acc: 0.7432
Epoch 165/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5293 - acc: 0.7425
Epoch 166/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5306 - acc: 0.7430
Epoch 167/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5315 - acc: 0.7428
Epoch 168/200
25724/25724 [==============================] - ETA: 0s - loss: 0.5288 - acc: 0.743 - 1s 27us/sample - loss: 0.5292 - acc: 0.7433
Epoch 169/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5287 - acc: 0.7430
Epoch 170/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5290 - acc: 0.74280s - loss: 0.5265 - acc: 0
Epoch 171/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5290 - acc: 0.7427
Epoch 172/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5290 - acc: 0.7429
Epoch 173/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5295 - acc: 0.7434
Epoch 174/200
25724/25724 [==============================] - 1s 30us/sample - loss: 0.5291 - acc: 0.7435
Epoch 175/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5343 - acc: 0.7428
Epoch 176/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5289 - acc: 0.7434
Epoch 177/200
25724/25724 [==============================] - 1s 28us/sample - loss: 0.5283 - acc: 0.7437
Epoch 178/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5281 - acc: 0.7432
Epoch 179/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5289 - acc: 0.7429
Epoch 180/200
25724/25724 [==============================] - 1s 29us/sample - loss: 0.5295 - acc: 0.7430
Epoch 181/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5286 - acc: 0.7430
Epoch 182/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5285 - acc: 0.7430
Epoch 183/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5284 - acc: 0.7433
Epoch 184/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5286 - acc: 0.7424
Epoch 185/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5290 - acc: 0.7430
Epoch 186/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5287 - acc: 0.7428
Epoch 187/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5290 - acc: 0.7422
Epoch 188/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5288 - acc: 0.7427
Epoch 189/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5290 - acc: 0.7432
Epoch 190/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5291 - acc: 0.7429
Epoch 191/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5282 - acc: 0.7426
Epoch 192/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5289 - acc: 0.7424
Epoch 193/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5299 - acc: 0.7429
Epoch 194/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5300 - acc: 0.7427
Epoch 195/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5291 - acc: 0.7434
Epoch 196/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5283 - acc: 0.74280s - loss: 0.5277
Epoch 197/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5287 - acc: 0.7432
Epoch 198/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5283 - acc: 0.7428
Epoch 199/200
25724/25724 [==============================] - 1s 27us/sample - loss: 0.5287 - acc: 0.7434
Epoch 200/200
25724/25724 [==============================] - 1s 26us/sample - loss: 0.5289 - acc: 0.7434
8575/8575 - 0s - loss: 0.5687 - acc: 0.7250
Loss: 0.5686979130892295, Accuracy: 0.7250145673751831

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random forest predictive accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Random forest predictive accuracy: 0.710